### ISSUE TITLE
Progress indicator bar not showing

### ISSUE THREAD

**Issue by cdbenj** [digitalnsw/nsw-design-system-react#10]
The markup for the bar isn't being rendered as well

![Screen Shot 2021-07-22 at 4 21 43 pm](https://user-images.githubusercontent.com/72421923/126597381-f2e28c6b-24f7-4e9a-897f-75bef03fec5e.png)

**Comment by tjharrop** [comment]
Seems to work in storybook, but not the example app 🤔
