### ISSUE TITLE
Accordion does not re-render when properties are changed.

### ISSUE THREAD

**Issue by EPurwanto** [digitalnsw/nsw-design-system-react#11]
The accordion component doesn't update when the values passed into it are changed. 

I've created a demo that shows this. https://codesandbox.io/s/nsw-ds-react-accordian-3nr7l?file=/src/App.js
The value entered into the textbox should show up in the "raw value", header and body. Instead only the "raw" value updates.

Also side note, the component should really take in children, rather than a "body" prop.

**Comment by EPurwanto** [comment]
Found the cause of the problem, props are being read in the constructor and then stored on the class. The stored copy is then used at render time. Changing to direct props access at render resolves the issue. 

I've made a PR with the fix.

**Comment by cdbenj** [comment]
Hey @EPurwanto thanks a lot for this and apologies for the delay. I've merged the PR and the fix is a available in v0.2.2.
