### ISSUE TITLE
Header component issues

### ISSUE THREAD

**Issue by cdbenj** [digitalnsw/nsw-design-system-react#7]
- There's no guiding docs showing how to use your own logo. 
- Hide search doesn't work

**Comment by resh-ie** [comment]
I had the same issue as well.
I was wondering if there were any solutions to this? 
Or is the solution just to create our custom header component?

**Comment by cdbenj** [comment]
Hi @Reshma-M-A 

Leave it with me. I'm going to have a look at this issue.

Cheers,
Ben

**Comment by cdbenj** [comment]
Hi @Reshma-M-A 

I've addressed the issues found in the [header](https://digitalnsw.github.io/nsw-design-system-react) component. Please update to `v0.2.1`


Cheers,
Ben :)

**Comment by resh-ie** [comment]
@cdbenj Awesome! Thank you so much for all your wonderful help!

**Comment by cdbenj** [comment]
You are welcome. Please don't hesitate to report any issues if you find one.
